buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
        maven { url "https://jitpack.io" }
        maven { url "https://dl.bintray.com/wasabeef/maven" }
        maven { url "https://dl.bintray.com/everything-android/maven" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
