ext {
    SONAR_HOST = project.hasProperty('sonarHost') ? project.getProperty('sonarHost') : 'http://localhost:9000'
}

sonar {
    properties {
        property 'sonar.projectName', android.defaultConfig.applicationId
        property 'sonar.projectKey', android.defaultConfig.applicationId + android.defaultConfig.versionName
        property 'sonar.sourceEncoding', 'UTF-8'
        property 'sonar.host.url', SONAR_HOST

        property 'sonar.sources', 'src/main/'
        property 'sonar.tests', 'src/test/,src/androidTest/'
        property 'sonar.exclusions', 'build/**,**/*.png,**/*generated*'

        property 'sonar.java.binaries', "${project.buildDir}/intermediates/javac/debug/classes"
        property 'sonar.java.test.binaries', "${project.buildDir}/intermediates/javac/debugUnitTest/classes"

        property 'sonar.coverage.jacoco.xmlReportPaths', "${project.buildDir}/reports/jacoco/jacoco.xml"
        property 'sonar.android.lint.report', "${project.buildDir}/reports/lint-results-debug.xml"
    }
}
